"""
Dynamic Industry Questions Manager

Manages industry-specific discovery questions that can be:
- Pre-loaded from configuration
- Added dynamically based on customer data
- Generated by AI based on context
"""

import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional
from datetime import datetime


logger = logging.getLogger(__name__)


# Default industry questions focused on Compute Orchestration
DEFAULT_QUESTIONS = {
    "technology": [
        {
            "question": "What is your current cloud infrastructure and GPU usage?",
            "category": "compute",
            "importance": "critical",
            "compute_relevant": True,
            "follow_ups": [
                "What cloud providers do you use?",
                "What GPU types are you currently running?",
                "What is your monthly cloud spend?"
            ]
        },
        {
            "question": "What AI/ML workloads are you running today?",
            "category": "technical",
            "importance": "high",
            "compute_relevant": True,
            "follow_ups": [
                "Training vs inference split?",
                "Model sizes and types?",
                "Batch vs real-time processing?"
            ]
        },
        {
            "question": "What are your performance requirements (latency, throughput)?",
            "category": "technical",
            "importance": "high",
            "compute_relevant": True,
            "follow_ups": [
                "What latency is acceptable?",
                "Peak throughput requirements?",
                "SLA requirements?"
            ]
        },
        {
            "question": "What is your AI/ML budget allocation for the next 12 months?",
            "category": "budget",
            "importance": "critical",
            "compute_relevant": True,
            "follow_ups": [
                "CapEx vs OpEx preference?",
                "Annual commitment capability?",
                "Budget approval process?"
            ]
        },
        {
            "question": "How do you handle scaling for AI workloads?",
            "category": "compute",
            "importance": "high",
            "compute_relevant": True,
            "follow_ups": [
                "Auto-scaling requirements?",
                "Peak vs baseline usage ratio?",
                "Growth projections?"
            ]
        },
    ],
    "retail": [
        {
            "question": "What visual AI use cases are you implementing (search, recommendations, etc.)?",
            "category": "business",
            "importance": "high",
            "compute_relevant": True,
            "follow_ups": [
                "Volume of images processed daily?",
                "Real-time vs batch requirements?",
                "Model complexity needs?"
            ]
        },
        {
            "question": "What is your product catalog size and update frequency?",
            "category": "technical",
            "importance": "medium",
            "compute_relevant": True,
            "follow_ups": [
                "Images per product?",
                "Re-indexing frequency?",
                "Storage requirements?"
            ]
        },
        {
            "question": "What are your peak traffic periods and scaling needs?",
            "category": "compute",
            "importance": "critical",
            "compute_relevant": True,
            "follow_ups": [
                "Holiday season scaling?",
                "Flash sale handling?",
                "Geographic distribution?"
            ]
        },
        {
            "question": "What is your current infrastructure spend on AI/ML?",
            "category": "budget",
            "importance": "critical",
            "compute_relevant": True,
            "follow_ups": [
                "Current GPU costs?",
                "Comparison shopping done?",
                "Budget flexibility for reservations?"
            ]
        },
    ],
    "healthcare": [
        {
            "question": "What are your data residency and compliance requirements?",
            "category": "compliance",
            "importance": "critical",
            "compute_relevant": True,
            "follow_ups": [
                "HIPAA requirements?",
                "On-premise vs cloud preference?",
                "Data sovereignty needs?"
            ]
        },
        {
            "question": "What medical imaging workloads do you need to support?",
            "category": "technical",
            "importance": "high",
            "compute_relevant": True,
            "follow_ups": [
                "Image modalities (CT, MRI, X-ray)?",
                "Volume per day?",
                "Model types needed?"
            ]
        },
        {
            "question": "What are your uptime and availability requirements?",
            "category": "compute",
            "importance": "critical",
            "compute_relevant": True,
            "follow_ups": [
                "SLA requirements?",
                "Disaster recovery needs?",
                "Redundancy requirements?"
            ]
        },
        {
            "question": "What is your timeline for AI deployment and budget cycle?",
            "category": "budget",
            "importance": "high",
            "compute_relevant": True,
            "follow_ups": [
                "Pilot vs production timeline?",
                "Budget approval authority?",
                "Multi-year commitment possible?"
            ]
        },
    ],
    "financial": [
        {
            "question": "What are your regulatory and compliance requirements for AI infrastructure?",
            "category": "compliance",
            "importance": "critical",
            "compute_relevant": True,
            "follow_ups": [
                "Data residency requirements?",
                "Audit trail needs?",
                "Vendor assessment process?"
            ]
        },
        {
            "question": "What real-time processing requirements do you have?",
            "category": "technical",
            "importance": "critical",
            "compute_relevant": True,
            "follow_ups": [
                "Transaction processing latency?",
                "Fraud detection speed requirements?",
                "Market data processing needs?"
            ]
        },
        {
            "question": "What is your GPU infrastructure strategy?",
            "category": "compute",
            "importance": "critical",
            "compute_relevant": True,
            "follow_ups": [
                "Current GPU spend?",
                "On-prem vs cloud mix?",
                "Reserved capacity interest?"
            ]
        },
        {
            "question": "What is your procurement process for infrastructure commitments?",
            "category": "budget",
            "importance": "high",
            "compute_relevant": True,
            "follow_ups": [
                "Approval levels for yearly commitments?",
                "Vendor qualification process?",
                "Contract terms flexibility?"
            ]
        },
    ],
    "manufacturing": [
        {
            "question": "What edge computing requirements do you have for factory floor AI?",
            "category": "compute",
            "importance": "critical",
            "compute_relevant": True,
            "follow_ups": [
                "Latency requirements?",
                "Connectivity constraints?",
                "Edge vs cloud processing split?"
            ]
        },
        {
            "question": "What is your quality inspection volume and throughput needs?",
            "category": "technical",
            "importance": "high",
            "compute_relevant": True,
            "follow_ups": [
                "Units inspected per hour?",
                "Camera/sensor count?",
                "Defect detection accuracy needs?"
            ]
        },
        {
            "question": "What is your infrastructure investment cycle?",
            "category": "budget",
            "importance": "critical",
            "compute_relevant": True,
            "follow_ups": [
                "CapEx budget availability?",
                "Multi-year planning horizon?",
                "ROI requirements?"
            ]
        },
        {
            "question": "How do you handle AI workloads across multiple facilities?",
            "category": "compute",
            "importance": "high",
            "compute_relevant": True,
            "follow_ups": [
                "Number of facilities?",
                "Centralized vs distributed processing?",
                "Network connectivity?"
            ]
        },
    ],
    "media": [
        {
            "question": "What content processing volumes do you handle?",
            "category": "technical",
            "importance": "critical",
            "compute_relevant": True,
            "follow_ups": [
                "Hours of video per day?",
                "Image processing volume?",
                "Real-time vs batch split?"
            ]
        },
        {
            "question": "What are your transcoding and processing GPU needs?",
            "category": "compute",
            "importance": "critical",
            "compute_relevant": True,
            "follow_ups": [
                "Current GPU infrastructure?",
                "Peak processing requirements?",
                "Quality tiers supported?"
            ]
        },
        {
            "question": "What is your content delivery timeline and infrastructure budget?",
            "category": "budget",
            "importance": "high",
            "compute_relevant": True,
            "follow_ups": [
                "Time-to-publish requirements?",
                "Infrastructure cost targets?",
                "Scaling budget for growth?"
            ]
        },
    ],
}


# Compute-specific questions applicable to all industries
COMPUTE_ORCHESTRATION_QUESTIONS = [
    {
        "question": "Have you evaluated the cost difference between on-demand and reserved GPU capacity?",
        "category": "compute",
        "importance": "critical",
        "compute_relevant": True,
        "follow_ups": [
            "Current on-demand spend?",
            "Awareness of 40-60% savings potential?",
            "Interest in cost predictability?"
        ]
    },
    {
        "question": "What is your GPU utilization pattern - consistent or variable?",
        "category": "compute",
        "importance": "critical",
        "compute_relevant": True,
        "follow_ups": [
            "Average utilization percentage?",
            "Peak vs baseline ratio?",
            "Predictability of demand?"
        ]
    },
    {
        "question": "Who manages your current AI infrastructure and what is the overhead?",
        "category": "compute",
        "importance": "high",
        "compute_relevant": True,
        "follow_ups": [
            "FTEs dedicated to infrastructure?",
            "Time spent on maintenance?",
            "Interest in managed services?"
        ]
    },
    {
        "question": "What would guaranteed GPU availability be worth to your business?",
        "category": "business",
        "importance": "high",
        "compute_relevant": True,
        "follow_ups": [
            "Impact of GPU unavailability?",
            "Revenue tied to AI services?",
            "SLA requirements?"
        ]
    },
    {
        "question": "Are you able to make 1-3 year infrastructure commitments for significant savings?",
        "category": "budget",
        "importance": "critical",
        "compute_relevant": True,
        "follow_ups": [
            "Budget approval process?",
            "Multi-year commitment authority?",
            "Preference for CapEx vs OpEx?"
        ]
    },
]


class IndustryQuestionManager:
    """
    Manages industry-specific discovery questions.
    
    Questions can be:
    - Loaded from default configuration
    - Added dynamically via API
    - Generated by AI based on customer context
    - Persisted to disk for reuse
    """
    
    def __init__(self, storage_path: str = "config/industry_questions.json"):
        self.storage_path = Path(storage_path)
        self.questions: Dict[str, List[Dict[str, Any]]] = {}
        self._load_questions()
    
    def _load_questions(self):
        """Load questions from storage or defaults."""
        if self.storage_path.exists():
            try:
                self.questions = json.loads(self.storage_path.read_text())
                logger.info(f"Loaded {sum(len(q) for q in self.questions.values())} questions from storage")
            except Exception as e:
                logger.error(f"Error loading questions: {e}")
                self.questions = DEFAULT_QUESTIONS.copy()
        else:
            self.questions = DEFAULT_QUESTIONS.copy()
            self._save_questions()
    
    def _save_questions(self):
        """Save questions to storage."""
        self.storage_path.parent.mkdir(parents=True, exist_ok=True)
        self.storage_path.write_text(json.dumps(self.questions, indent=2))
    
    def get_questions(self, industry: str) -> List[Dict[str, Any]]:
        """
        Get questions for an industry.
        
        Includes:
        - Industry-specific questions
        - Universal compute orchestration questions
        """
        industry_lower = industry.lower()
        
        # Get industry-specific questions
        questions = self.questions.get(industry_lower, []).copy()
        
        # Add compute orchestration questions if not already present
        existing_texts = {q["question"] for q in questions}
        for compute_q in COMPUTE_ORCHESTRATION_QUESTIONS:
            if compute_q["question"] not in existing_texts:
                questions.append(compute_q)
        
        # Sort by importance
        importance_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
        questions.sort(key=lambda x: importance_order.get(x.get("importance", "medium"), 2))
        
        return questions
    
    def add_questions(
        self,
        industry: str,
        questions: List[Dict[str, Any]],
        source: Optional[str] = None
    ):
        """
        Add new questions to an industry.
        
        Args:
            industry: Industry name
            questions: List of question dictionaries
            source: Source of the questions (e.g., "customer_xyz", "ai_generated")
        """
        industry_lower = industry.lower()
        
        if industry_lower not in self.questions:
            self.questions[industry_lower] = []
        
        # Add metadata and deduplicate
        existing_texts = {q["question"] for q in self.questions[industry_lower]}
        
        for q in questions:
            if q["question"] not in existing_texts:
                q["added_at"] = datetime.now().isoformat()
                q["source"] = source
                self.questions[industry_lower].append(q)
                existing_texts.add(q["question"])
        
        self._save_questions()
        logger.info(f"Added {len(questions)} questions to {industry}")
    
    def list_industries(self) -> List[Dict[str, Any]]:
        """List all industries with question counts."""
        return [
            {
                "industry": industry,
                "question_count": len(questions),
                "compute_questions": sum(1 for q in questions if q.get("compute_relevant")),
            }
            for industry, questions in self.questions.items()
        ]
    
    def get_compute_focused_questions(self, industry: str) -> List[Dict[str, Any]]:
        """Get only compute-relevant questions for an industry."""
        all_questions = self.get_questions(industry)
        return [q for q in all_questions if q.get("compute_relevant")]
    
    def suggest_questions_from_context(
        self,
        industry: str,
        context: Dict[str, Any]
    ) -> List[Dict[str, Any]]:
        """
        Suggest relevant questions based on customer context.
        
        This filters existing questions based on what's most relevant
        to the specific customer situation.
        """
        all_questions = self.get_questions(industry)
        
        # Score questions based on context relevance
        scored_questions = []
        
        for q in all_questions:
            score = 0
            
            # Prioritize compute questions if compute requirements mentioned
            if context.get("compute_requirements") and q.get("compute_relevant"):
                score += 3
            
            # Prioritize budget questions if budget mentioned
            if context.get("budget_range") and q.get("category") == "budget":
                score += 2
            
            # Prioritize critical questions
            if q.get("importance") == "critical":
                score += 2
            elif q.get("importance") == "high":
                score += 1
            
            scored_questions.append((score, q))
        
        # Sort by score and return top questions
        scored_questions.sort(key=lambda x: x[0], reverse=True)
        return [q for _, q in scored_questions[:15]]
    
    def export_questions(self, industry: Optional[str] = None) -> str:
        """Export questions as markdown."""
        output = ["# Industry Discovery Questions\n"]
        
        industries = [industry] if industry else self.questions.keys()
        
        for ind in industries:
            if ind not in self.questions:
                continue
            
            output.append(f"\n## {ind.title()}\n")
            
            for q in self.questions[ind]:
                output.append(f"\n### {q['question']}")
                output.append(f"\n**Category:** {q.get('category', 'general')} | "
                            f"**Importance:** {q.get('importance', 'medium')} | "
                            f"**Compute Relevant:** {'Yes' if q.get('compute_relevant') else 'No'}")
                
                if q.get("follow_ups"):
                    output.append("\n**Follow-up Questions:**")
                    for fu in q["follow_ups"]:
                        output.append(f"- {fu}")
                
                output.append("")
        
        return "\n".join(output)
