import os
import sys

sys.path.append(os.path.dirname(__file__))
from typing import Iterator, List

from clarifai.runners.models.model_builder import ModelBuilder
from clarifai.runners.models.openai_class import OpenAIModelClass
from clarifai.runners.utils.data_types import Audio, Image, Video
from clarifai.runners.utils.data_utils import Param
from clarifai.runners.utils.openai_convertor import build_openai_messages
from clarifai.utils.logging import logger
from openai import OpenAI
from openai_server_starter import OpenAI_APIServer


class MyRunner(OpenAIModelClass):
    """
    A custom runner that integrates with the Clarifai platform and uses Server inference
    to process inputs, including text, images, audios & videos.
    """

    client = True  # This will be set in load_model method
    model = True  # This will be set in load_model method

    def load_model(self):
        """Load the model here and start the  server."""
        os.path.join(os.path.dirname(__file__))

        server_args = {
            'max_model_len': '16000',
            'gpu_memory_utilization': 0.9,
            'dtype': 'auto',
            'task': 'auto',
            'kv_cache_dtype': 'auto',
            'tensor_parallel_size': 1,
            'chat_template': None,
            'cpu_offload_gb': 0.0,
            'quantization': None,
            'port': 23333,
            'host': 'localhost',
            'checkpoints': 'openbmb/MiniCPM-o-2_6'
        }

        stage = server_args.get("checkpoints")
        if stage in ["build", "runtime"]:
            config_path = os.path.dirname(os.path.dirname(__file__))
            builder = ModelBuilder(config_path, download_validation_only=True)
            checkpoints = builder.download_checkpoints(stage=stage)
            server_args.update({"checkpoints": checkpoints})

        if server_args.get("additional_list_args") == ['']:
            server_args.pop("additional_list_args")

        # Start server
        # This line were generated by `upload` module
        self.server = OpenAI_APIServer.from_vllm_backend(**server_args)

        self.client = OpenAI(
            api_key="notset",
            base_url=MyRunner.make_api_url(self.server.host, self.server.port))
        # Give the model registry a brief moment, then fetch model ID with retries
        self.model = self._get_model()

        logger.info(f"OpenAI {self.model} model loaded successfully!")

    def _get_model(self):
        last_err = None
        for attempt in range(1, 11):
            try:
                models = self.client.models.list().data
                if models:
                    return models[0].id
                else:
                    last_err = RuntimeError("No models returned by server")
            except Exception as e:
                last_err = e
            # Backoff a bit before retrying
            import time
            time.sleep(min(0.25 * attempt, 2.0))
        raise ConnectionError("Failed to retrieve model ID from API after retries") from last_err

    @staticmethod
    def make_api_url(host: str, port: int, version: str = "v1") -> str:
        return f"http://{host}:{port}/{version}"

    @OpenAIModelClass.method
    def predict(self,
                prompt: str,
                image: Image = None,
                images: List[Image] = None,
                audio: Audio = None,
                audios: List[Audio] = None,
                video: Video = None,
                videos: List[Video] = None,
                chat_history: List[dict] = None,
                max_tokens: int = Param(default=512, description="The maximum number of tokens to generate. Shorter token lengths will provide faster performance.", ),
                temperature: float = Param(default=0.7, description="A decimal number that determines the degree of randomness in the response", ),
                top_p: float = Param(default=0.95, description="An alternative to sampling with temperature, where the model considers the results of the tokens with top_p probability mass.", )
                ) -> str:
        """This is the method that will be called when the runner is run. It takes in an input and
        returns an output.
        """
        openai_messages = build_openai_messages(prompt=prompt, image=image, images=images, audio=audio, audios=audios, video=video, videos=videos, messages=chat_history)
        response = self.client.chat.completions.create(
            model=self.model,
            messages=openai_messages,
            max_completion_tokens=max_tokens,
            temperature=temperature,
            top_p=top_p)
        if response.usage and response.usage.prompt_tokens and response.usage.completion_tokens:
            self.set_output_context(prompt_tokens=response.usage.prompt_tokens, completion_tokens=response.usage.completion_tokens)
        return response.choices[0].message.content

    @OpenAIModelClass.method
    def generate(self,
                prompt: str,
                image: Image = None,
                images: List[Image] = None,
                audio: Audio = None,
                audios: List[Audio] = None,
                video: Video = None,
                videos: List[Video] = None,
                chat_history: List[dict] = None,
                max_tokens: int = Param(default=512, description="The maximum number of tokens to generate. Shorter token lengths will provide faster performance.", ),
                temperature: float = Param(default=0.7, description="A decimal number that determines the degree of randomness in the response", ),
                top_p: float = Param(default=0.95, description="An alternative to sampling with temperature, where the model considers the results of the tokens with top_p probability mass.", )
                ) -> Iterator[str]:
        """Example yielding a whole batch of streamed stuff back."""
        openai_messages = build_openai_messages(prompt=prompt, image=image, images=images, audio=audio, audios=audios, video=video, videos=videos, messages=chat_history)
        for chunk in self.client.chat.completions.create(
            model=self.model,
            messages=openai_messages,
            max_completion_tokens=max_tokens,
            temperature=temperature,
            top_p=top_p,
            stream=True):
            if hasattr(chunk, 'usage') and chunk.usage is not None:
                if hasattr(chunk.usage, 'prompt_tokens') and hasattr(chunk.usage, 'completion_tokens'):
                    self.set_output_context(prompt_tokens=chunk.usage.prompt_tokens, completion_tokens=chunk.usage.completion_tokens)
            if chunk.choices:
                text = (chunk.choices[0].delta.content
                        if (chunk and chunk.choices[0].delta.content) is not None else '')
                yield text

    # This method is needed to test the model with the test-locally CLI command.
    def test(self):
        """Test the model here."""
        try:
            print("Testing predict...")
            # Test predict (text only)
            print(self.predict(prompt="Explain why cat can't fly"))
            # Test predict with image
            print(self.predict(prompt="Describe this image", image=Image.from_url("https://samples.clarifai.com/metro-north.jpg")))
            # Test predict with audio
            print(self.predict(prompt="Transcribe this audio", audio=Audio.from_url("https://samples.clarifai.com/GoodMorning.wav")))
        except Exception as e:
            # Surface recent server logs alongside the error
            logs = []
            try:
                logs = getattr(self.server, 'recent_logs', lambda n=50: [])(50)
            except Exception:
                pass
            print(f"Error in predict: {e}\nRecent server logs:\n" + "\n".join(logs))

        try:
            print("Testing generate...")
            # Test generate (text only)
            for each in self.generate(prompt="Explain why cat can't fly"):
                print(each, end=" ")
            print()
            # Test generate with image
            for each in self.generate(prompt="Describe this image", image=Image.from_url("https://samples.clarifai.com/metro-north.jpg")):
                print(each, end=" ")
            print()
            # Test generate with audio
            for each in self.generate(prompt="Transcribe this audio", audio=Audio.from_url("https://samples.clarifai.com/GoodMorning.wav")):
                print(each, end=" ")
            print()
        except Exception as e:
            logs = []
            try:
                logs = getattr(self.server, 'recent_logs', lambda n=50: [])(50)
            except Exception:
                pass
            print(f"Error in generate: {e}\nRecent server logs:\n" + "\n".join(logs))
