enabled: true

affinity: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60

config:
  cookieSecret: ""
  host: ""

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  runAsNonRoot: true
  runAsUser: 999

env: {}

image:
  pullPolicy: "IfNotPresent"
  pullSecrets: {}
  repository: "282244745782.dkr.ecr.us-east-1.amazonaws.com/clarifai/infra/helpers"
  tag: "module_video_stream"

ingress:
  enabled: false
  annotations: {}
  # Defaults to ingressNginx if className is not "alb"
  defaultAnnotations:
    ingressNginx:
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    alb:
      alb.ingress.kubernetes.io/target-type: "ip"
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:282244745782:certificate/76c5caad-3932-46a5-bb2a-a4501e5ca8c1"
  className: "alb"
  tls: {}

networkPolicy: true

livenessProbe:
  httpGet:
    path: "/healthz"
    port: "http"
  initialDelaySeconds: 15
  periodSeconds: 3
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

# onprem:
#   enabled: false
#   apiurl: http://go-api:8000
#   sdhurl: http://secure-data-host:443

podSecurityContext:
  fsGroup: 999
  seccompProfile:
    type: RuntimeDefault

readinessProbe:
  httpGet:
    path: "/healthz"
    port: "http"
  initialDelaySeconds: 15
  periodSeconds: 3
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

replicas: 1

resources:
  limits:
    cpu: "1"
    memory: "3000Mi"
  requests:
    cpu: "350m"
    memory: "1500Mi"
