apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-guacamole
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "guacamole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "guacamole.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: guacamole
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: guacamole
              containerPort: 8080
              protocol: TCP
            - name: vnc
              containerPort: 5901
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /home/vnc_user
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-guacamole
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}