apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-guacamole
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.guacamolePort }}
      targetPort: guacamole
      protocol: TCP
      name: guacamole
    - port: {{ .Values.service.vncPort }}
      targetPort: vnc
      protocol: TCP
      name: vnc
  selector:
    {{- include "guacamole.selectorLabels" . | nindent 4 }}