{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name | quote }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name | quote }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        {{- if .Values.onprem.enabled }}
        - name: ON_PREM
          value: "True"
        - name: ON_PREM_API_URL
          value: {{ .Values.onprem.apiurl }}
        - name: ON_PREM_SDH_URL
          value: {{ .Values.onprem.sdhurl }}
        {{- end }}
        - name: STREAMLIT_BROWSER_SERVER_ADDRESS
          value: {{ .Values.config.host | quote }}
        - name: STREAMLIT_SERVER_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name | quote }}
              key: cookieSecret
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | squote }}
        {{- end }}
        ports:
        - name: "http"
          containerPort: 8501
          protocol: "TCP"
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{ end }}
