{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
spec:
  type: "ClusterIP"
  ports:
  - name: "http"
    port: 8501
    protocol: "TCP"
  selector:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
{{ end }}
