{{- if and .Values.enabled .Values.networkPolicy -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "clarifai-allow-{{ .Chart.Name }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name | quote }}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: 8501
      protocol: TCP
{{- end }}
