SYSTEM_INSTRUCTION = (
    "You are a professional video analysis expert. Your task is to analyze sports, event, and surveillance videos frame by frame. "
    "You are only provided with one frame per second from the video, not every single frame so you need to use the previous frames to help you understand the action of the current frame if provided."
    "Do not assume the previous frame's events are currently in progress. They may be in progress or they may be completed."
    "For each frame, carefully follow the specific instructions provided for the selected category, and return your answer strictly in the requested JSON format. "
    "Be concise, accurate, and avoid speculation. If information is not visible in the frame, state so clearly."
    "Colors, shapes, sizes, types and other traits are important as well as the actions of the objects in the frame. Ensure you give details on these."
)

PROMPTS = {
    "bronc_riding": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this bronc riding frame and provide:\n1. Category (should be 'bronc riding')\n2. Rider performance\n3. Horse behavior\n4. Safety concerns\n5. Current score/time\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"bronc riding\",\n    \"performance\": \"description\",\n    \"horse_behavior\": \"description\",\n    \"safety\": \"description\",\n    \"score\": \"score/time\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "bull_riding": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this bull riding frame and provide:\n1. Category (should be 'bull riding')\n2. Rider performance\n3. Bull behavior\n4. Safety concerns\n5. Current score/time\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"bull riding\",\n    \"performance\": \"description\",\n    \"bull_behavior\": \"description\",\n    \"safety\": \"description\",\n    \"score\": \"score/time\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "barrel_racing": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this barrel racing frame and provide:\n1. Category (should be 'barrel racing')\n2. Rider performance\n3. Horse behavior\n4. Barrel position\n5. Current score/time\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"barrel racing\",\n    \"performance\": \"description\",\n    \"horse_behavior\": \"description\",\n    \"barrel_position\": \"description\",\n    \"score\": \"score/time\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "sheep_riding": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this sheep riding (mutton busting) frame and provide:\n1. Category (should be 'sheep riding')\n2. Child's performance\n3. Sheep behavior\n4. Safety concerns\n5. Current score/time\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"sheep riding\",\n    \"performance\": \"description\",\n    \"sheep_behavior\": \"description\",\n    \"safety\": \"description\",\n    \"score\": \"score/time\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "football": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this football game frame and provide:\n1. Category (should be 'football')\n2. Current play type (e.g., run, pass, special teams)\n3. Ball carrier/quarterback location\n4. Field position (e.g., red zone, midfield)\n5. Key players involved\n6. Confidence score (0-1)\n7. Brief reasoning to include moment of snap or tackle\n\nFormat the response as JSON:\n{{\n    \"category\": \"football\",\n    \"play_type\": \"type\",\n    \"ball_location\": \"location\",\n    \"field_position\": \"position\",\n    \"key_players\": [\"player1\", \"player2\"],\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "basketball": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this basketball game frame and provide:\n1. Category (should be 'basketball')\n2. Current play type (e.g., fast break, set play, defense)\n3. Ball possession (team name or \"neutral\")\n4. Ball location on court\n5. Key players involved\n6. Confidence score (0-1)\n7. Brief reasoning to include any special plays or techniques such as a pick and roll or players in purgatory. Ensure you provide location of all players\n\nFormat the response as JSON:\n{{\n    \"category\": \"basketball\",\n    \"play_type\": \"type\",\n    \"possession\": \"team\",\n    \"ball_location\": \"location\",\n    \"key_players\": [\"player1\", \"player2\"],\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "soccer": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this soccer frame and provide:\n1. Category (should be 'soccer')\n2. Current play type (e.g., attack, defense, set piece)\n3. Ball location\n4. Key players involved\n5. Field position\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"soccer\",\n    \"play_type\": \"type\",\n    \"ball_location\": \"location\",\n    \"key_players\": [\"player1\", \"player2\"],\n    \"field_position\": \"position\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "baseball": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this baseball frame and provide:\n1. Category (should be 'baseball')\n2. Current play type (e.g., pitch, hit, fielding)\n3. Ball location\n4. Key players involved\n5. Base positions\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"baseball\",\n    \"play_type\": \"type\",\n    \"ball_location\": \"location\",\n    \"key_players\": [\"player1\", \"player2\"],\n    \"base_positions\": \"description\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "hockey": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this hockey frame and provide:\n1. Category (should be 'hockey')\n2. Current play type (e.g., power play, penalty kill)\n3. Puck location\n4. Key players involved\n5. Zone (offensive, defensive, neutral)\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"hockey\",\n    \"play_type\": \"type\",\n    \"puck_location\": \"location\",\n    \"key_players\": [\"player1\", \"player2\"],\n    \"zone\": \"zone\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "military_surveillance": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this surveillance/military video frame and provide:\n1. Category (should be 'military surveillance')\n2. Detected objects (e.g., vehicles, personnel, weapons)\n3. Activities observed\n4. Potential threats\n5. Location (if available)\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"military surveillance\",\n    \"detected_objects\": [\"object1\", \"object2\"],\n    \"activities\": [\"activity1\", \"activity2\"],\n    \"threats\": [\"threat1\", \"threat2\"],\n    \"location\": \"description\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "public_safey": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this surveillance video frame and provide:\n1. Category (should be 'public surveillance')\n2. Detected objects (e.g., vehicles, personnel, protective gear)\n3. Activities observed\n4. Potential dangers\n5. Location (if available)\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"public safety\",\n    \"detected_objects\": [\"object1\", \"object2\"],\n    \"activities\": [\"activity1\", \"activity2\"],\n    \"dangers\": [\"danger1\", \"danger2\"],\n    \"location\": \"description\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "flare_safety": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this stack flare any time flare fall below stack top, it is endager of stack explosion video frame and provide:\n1. Category (should be 'stack surveillance')\n2. Detected objects (e.g., safe flare when no part of stack inside the flare, danger flare when the fire burn any part of stack)\n3. Activities observed\n4. Potential dangers\n5. Location (if available)\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"stack safety\",\n    \"detected_objects\": [\"object1\", \"object2\"],\n    \"activities\": [\"activity1\", \"activity2\"],\n    \"dangers\": [\"danger1\", \"danger2\"],\n    \"location\": \"description\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "security": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this security surveillance frame for shoplifting or stealing behavior and provide:\n1. Category (should be 'security')\n2. Event type ('shoplifting' if stealing detected, 'normal' if no suspicious activity)\n3. Suspicious persons and their actions (only list persons exhibiting suspicious behavior)\n4. Person description (clothing, hat, accessories, physical characteristics like height/build, hair color, etc.)\n5. Suspicious behaviors observed (e.g., concealing items, looking around nervously, putting items in bags/pockets)\n6. Items involved (if any)\n7. Body location of concealed items (e.g., 'in jacket pocket', 'under shirt', 'in pants waistband', 'in bag/purse', 'in sleeve', 'under jacket', 'in backpack', 'none visible')\n8. Location in frame (e.g., near checkout, in aisles, at entrance/exit)\n9. Confidence score (0-1)\n10. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"security\",\n    \"event\": \"shoplifting\" or \"normal\",\n    \"suspicious_persons\": [\"person1_suspicious_action\", \"person2_suspicious_action\"],\n    \"person_description\": \"detailed description of clothing, hat, accessories, physical appearance\",\n    \"suspicious_behaviors\": [\"behavior1\", \"behavior2\"],\n    \"items_involved\": [\"item1\", \"item2\"],\n    \"concealment_location\": \"body location where items are hidden\",\n    \"location\": \"description\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "fish_analysis": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this video frame for fish identification and counting. Provide detailed information about:\n1. Category (should be 'fish analysis')\n2. Fish species identified (provide specific species names if recognizable, e.g., 'Clownfish', 'Bluefin Tuna', 'Goldfish')\n3. Total fish count (exact number of individual fish visible in this frame)\n4. Fish locations (describe where each fish or group is positioned - e.g., 'top left', 'center', 'bottom right', 'near coral', 'swimming left to right')\n5. Fish sizes (relative sizes - e.g., 'small', 'medium', 'large', or estimated length if possible)\n6. Fish behavior (e.g., 'swimming', 'feeding', 'schooling', 'stationary', 'darting')\n7. Environmental context (e.g., 'coral reef', 'open water', 'aquarium', 'murky water', 'clear water')\n8. Image quality assessment:\n   - Overall quality (e.g., 'excellent', 'good', 'fair', 'poor')\n   - Sharpness (e.g., 'sharp', 'slightly blurred', 'blurred', 'very blurred')\n   - Lighting conditions (e.g., 'well-lit', 'bright', 'dim', 'dark', 'overexposed', 'underexposed', 'backlit')\n   - Water clarity (e.g., 'crystal clear', 'clear', 'slightly murky', 'murky', 'very murky')\n   - Visibility issues (e.g., 'no issues', 'glare', 'reflections', 'particles in water', 'low contrast')\n   - Quality confidence (0-1): How confident you are in the image quality assessment\n9. Fish detection confidence (0-1): How confident you are in the fish identification and counting\n10. Brief reasoning\n\nBe thorough and count each individual fish carefully. If fish are partially visible or overlapping, make your best estimate and note the uncertainty in reasoning.\n\nFormat the response as JSON:\n{{\n    \"category\": \"fish analysis\",\n    \"fish_species\": [\"species1\", \"species2\"],\n    \"total_count\": 0,\n    \"fish_details\": [\n        {{\n            \"species\": \"species_name\",\n            \"count\": 0,\n            \"locations\": [\"location1\", \"location2\"],\n            \"sizes\": [\"size1\", \"size2\"],\n            \"behavior\": \"description\",\n            \"confidence\": 0.95\n        }}\n    ],\n    \"environment\": \"description\",\n    \"image_quality\": {{\n        \"overall\": \"quality_rating\",\n        \"sharpness\": \"sharpness_level\",\n        \"lighting\": \"lighting_condition\",\n        \"water_clarity\": \"clarity_level\",\n        \"visibility_issues\": [\"issue1\", \"issue2\"],\n        \"confidence\": 0.95\n    }},\n    \"reasoning\": \"explanation\"\n}}""",
    "general": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this frame and provide:\n1. Category (e.g., sport, event, or content type)\n2. The main category of content\n3. A rating (G, PG, PG-13, R)\n4. A confidence score (0-1)\n5. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"category\",\n    \"predicted_category\": \"category\",\n    \"predicted_rating\": \"rating\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
}
