build_info:
  python_version: '3.12'

inference_compute_info:
  cpu_limit: '1'
  cpu_memory: 1Gi
  num_accelerators: 0

model:
  app_id: iphone-layout-mcp-app
  id: iphone-layout-generator-local
  model_type_id: mcp
  user_id: mulder