#!/bin/bash

export XDG_RUNTIME_DIR="/tmp/runtime-vnc_user"
export DISPLAY=:1

export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

mkdir -p $XDG_RUNTIME_DIR
chmod 700 $XDG_RUNTIME_DIR

exec startxfce4