"""
WeasyPrint PDF Report Generator for Brand Compliance Analysis
Generates professional, emoji-enabled reports using HTML/CSS
"""

import io
import json
import base64
from datetime import datetime
from typing import List, Dict, Any
from weasyprint import HTML, CSS
from PIL import Image
import tempfile
import os


class WeasyPrintBrandComplianceReportGenerator:
    """
    Professional PDF report generator using WeasyPrint with full emoji support.
    Creates beautiful reports using HTML/CSS for maximum flexibility.
    """
    
    def __init__(self):
        self.page_count = 0
        
        # Professional CSS styles
        self.css_styles = """
        @page {
            size: A4;
            margin: 20mm;
            @bottom-center {
                content: "Report generated by AI Brand Compliance Specialist | Page " counter(page);
                font-family: Arial, sans-serif;
                font-size: 8pt;
                color: #6c757d;
            }
        }
        
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #212529;
            margin: 0;
            padding: 0;
        }
        
        .header-section {
            background: linear-gradient(135deg, #337ab7 0%, #5bc0de 100%);
            color: white;
            padding: 30px;
            text-align: center;
            border-radius: 10px;
            margin-bottom: 30px;
        }
        
        .main-title {
            font-size: 28pt;
            font-weight: bold;
            margin-bottom: 10px;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
        }
        
        .subtitle {
            font-size: 14pt;
            opacity: 0.9;
            margin-bottom: 0;
        }
        
        .summary-box {
            background: #f8f9fa;
            border: 2px solid #dee2e6;
            border-radius: 15px;
            padding: 25px;
            margin: 30px 0;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        
        .summary-title {
            font-size: 18pt;
            font-weight: bold;
            color: #337ab7;
            margin-bottom: 15px;
            text-align: center;
        }
        
        .summary-text {
            font-size: 12pt;
            margin-bottom: 20px;
            text-align: center;
        }
        
        .status-indicators {
            display: flex;
            justify-content: space-around;
            margin-top: 20px;
        }
        
        .status-item {
            text-align: center;
            padding: 10px;
        }
        
        .status-icon {
            font-size: 16pt;
            margin-right: 8px;
        }
        
        .compliant {
            color: #5cb85c;
        }
        
        .non-compliant {
            color: #d9534f;
        }
        
        .asset-overview {
            margin: 30px 0;
        }
        
        .section-title {
            font-size: 16pt;
            font-weight: bold;
            color: #337ab7;
            margin-bottom: 20px;
            border-bottom: 2px solid #337ab7;
            padding-bottom: 10px;
        }
        
        .asset-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 12px;
            margin-bottom: 8px;
            border-radius: 8px;
            background: #f8f9fa;
        }
        
        .asset-name {
            font-weight: bold;
            flex-grow: 1;
        }
        
        .status-badge {
            padding: 6px 12px;
            border-radius: 20px;
            color: white;
            font-weight: bold;
            font-size: 10pt;
        }
        
        .status-badge.compliant {
            background: #5cb85c;
        }
        
        .status-badge.non-compliant {
            background: #d9534f;
        }
        
        .page-break {
            page-break-before: always;
        }
        
        .asset-header {
            background: linear-gradient(90deg, #337ab7 0%, #5bc0de 100%);
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 10px;
            margin-bottom: 25px;
        }
        
        .asset-title {
            font-size: 18pt;
            font-weight: bold;
            margin: 0;
        }
        
        .image-container {
            text-align: center;
            margin: 25px 0;
            padding: 20px;
            background: #f8f9fa;
            border-radius: 10px;
            border: 1px solid #dee2e6;
        }
        
        .image-label {
            font-size: 14pt;
            font-weight: bold;
            color: #337ab7;
            margin-bottom: 15px;
        }
        
        .asset-image {
            max-width: 100%;
            max-height: 300px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.15);
        }
        
        .image-placeholder {
            color: #6c757d;
            font-style: italic;
            padding: 40px;
            background: #e9ecef;
            border-radius: 8px;
        }
        
        .status-banner {
            padding: 15px;
            border-radius: 10px;
            text-align: center;
            font-size: 16pt;
            font-weight: bold;
            margin: 25px 0;
            color: white;
        }
        
        .status-banner.compliant {
            background: linear-gradient(135deg, #5cb85c 0%, #4cae4c 100%);
        }
        
        .status-banner.non-compliant {
            background: linear-gradient(135deg, #d9534f 0%, #c9302c 100%);
        }
        
        .findings-section {
            margin: 30px 0;
        }
        
        .violation-item {
            background: #fff5f5;
            border-left: 5px solid #d9534f;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 0 8px 8px 0;
        }
        
        .violation-header {
            font-size: 14pt;
            font-weight: bold;
            color: #d9534f;
            margin-bottom: 15px;
        }
        
        .issue-section, .fix-section {
            margin: 15px 0;
        }
        
        .issue-label, .fix-label {
            font-weight: bold;
            color: #495057;
            margin-bottom: 8px;
            font-size: 11pt;
        }
        
        .issue-text {
            background: #f8f9fa;
            padding: 12px;
            border-radius: 5px;
            border-left: 3px solid #6c757d;
        }
        
        .fix-text {
            background: #e8f4fd;
            padding: 12px;
            border-radius: 5px;
            border-left: 3px solid #337ab7;
            color: #337ab7;
        }
        
        .compliant-message {
            background: linear-gradient(135deg, #f0fff4 0%, #e8f5e8 100%);
            border: 2px solid #5cb85c;
            border-radius: 15px;
            padding: 25px;
            text-align: center;
            margin: 25px 0;
        }
        
        .compliant-title {
            font-size: 16pt;
            font-weight: bold;
            color: #5cb85c;
            margin-bottom: 15px;
        }
        
        .recommendations {
            margin: 20px 0;
        }
        
        .recommendation-item {
            display: flex;
            margin: 10px 0;
            padding: 8px;
        }
        
        .recommendation-bullet {
            margin-right: 10px;
            color: #337ab7;
            font-weight: bold;
        }
        """
    
    def create_report(self, analysis_results: List[Dict[str, Any]], 
                     session_metadata: Dict[str, Any] = None) -> bytes:
        """Create a comprehensive PDF report using WeasyPrint."""
        print(f"🔍 DEBUG: ComplianceReportGenerator.create_report called with {len(analysis_results)} results")
        
        # Generate HTML content
        print("🔍 DEBUG: Generating HTML content...")
        html_content = self._generate_html(analysis_results, session_metadata)
        print(f"🔍 DEBUG: HTML content generated, length: {len(html_content)} chars")
        
        # Create PDF using WeasyPrint
        print("🔍 DEBUG: Creating PDF with WeasyPrint...")
        html_doc = HTML(string=html_content)
        css_doc = CSS(string=self.css_styles)
        
        pdf_bytes = html_doc.write_pdf(stylesheets=[css_doc])
        
        print(f"✅ PDF report generated successfully with WeasyPrint ({len(pdf_bytes)} bytes)")
        return pdf_bytes
    
    def _generate_html(self, analysis_results: List[Dict[str, Any]], 
                      session_metadata: Dict[str, Any]) -> str:
        """Generate the complete HTML content for the report."""
        
        # Calculate statistics
        total_assets = len(analysis_results)
        non_compliant_count = sum(1 for result in analysis_results 
                                if result.get('json_output', {}).get('compliance_status', '').lower() == 'non-compliant')
        compliant_count = total_assets - non_compliant_count
        
        current_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        
        html = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Brand Compliance Analysis Report</title>
        </head>
        <body>
            <!-- Cover Page -->
            <div class="header-section">
                <h1 class="main-title">🎯 Brand Compliance Analysis Report</h1>
                <p class="subtitle">📅 Generated on {current_date}</p>
            </div>
            
            <div class="summary-box">
                <h2 class="summary-title">📊 Executive Summary</h2>
                <p class="summary-text">
                    This report details the analysis of {total_assets} assets. 
                    {f"{non_compliant_count} asset{'s' if non_compliant_count != 1 else ''} were found to be non-compliant." if non_compliant_count > 0 else "All assets were found to be compliant with brand guidelines."}
                </p>
                
                <div class="status-indicators">
                    <div class="status-item compliant">
                        <span class="status-icon">✅</span>
                        <strong>Compliant: {compliant_count}</strong>
                    </div>
                    <div class="status-item non-compliant">
                        <span class="status-icon">⚠️</span>
                        <strong>Non-Compliant: {non_compliant_count}</strong>
                    </div>
                </div>
            </div>
            
            <div class="asset-overview">
                <h2 class="section-title">📋 Assets Analyzed</h2>
                {self._generate_asset_overview_html(analysis_results)}
            </div>
            
            <!-- Individual Asset Pages -->
            {self._generate_asset_pages_html(analysis_results)}
        </body>
        </html>
        """
        
        return html
    
    def _generate_asset_overview_html(self, analysis_results: List[Dict[str, Any]]) -> str:
        """Generate HTML for the asset overview section."""
        html = ""
        
        for i, result in enumerate(analysis_results, 1):
            filename = result.get('filename', f'Asset {i}')
            status = result.get('json_output', {}).get('compliance_status', 'Unknown')
            
            status_class = 'compliant' if status.lower() == 'compliant' else 'non-compliant'
            status_icon = '✅' if status.lower() == 'compliant' else '⚠️'
            
            html += f"""
            <div class="asset-item">
                <span class="asset-name">{i}. {filename}</span>
                <span class="status-badge {status_class}">
                    {status_icon} {status.upper()}
                </span>
            </div>
            """
        
        return html
    
    def _generate_asset_pages_html(self, analysis_results: List[Dict[str, Any]]) -> str:
        """Generate HTML for individual asset analysis pages."""
        html = ""
        
        for i, result in enumerate(analysis_results, 1):
            filename = result.get('filename', f'Asset {i}')
            json_output = result.get('json_output', {})
            compliance_status = json_output.get('compliance_status', 'Unknown')
            
            html += f"""
            <div class="page-break">
                <div class="asset-header">
                    <h1 class="asset-title">🔍 Analysis for: {filename}</h1>
                </div>
                
                {self._generate_image_html(result)}
                {self._generate_status_banner_html(compliance_status)}
                
                {self._generate_findings_html(json_output) if compliance_status.lower() == 'non-compliant' else self._generate_compliant_message_html(json_output)}
            </div>
            """
        
        return html
    
    def _generate_image_html(self, result: Dict[str, Any]) -> str:
        """Generate HTML for asset image display."""
        image_data = result.get('image_data')
        
        if not image_data:
            return """
            <div class="image-container">
                <div class="image-label">📷 Asset Preview</div>
                <div class="image-placeholder">
                    📷 Image preview not available
                </div>
            </div>
            """
        
        try:
            # Create temporary file for image
            with tempfile.NamedTemporaryFile(delete=False, suffix='.jpg') as tmp_file:
                if isinstance(image_data, str):
                    # Base64 encoded image
                    try:
                        image_bytes = base64.b64decode(image_data)
                    except Exception as e:
                        print(f"⚠️ Base64 decode error: {e}")
                        return self._generate_image_error_html()
                else:
                    # Raw bytes
                    image_bytes = image_data
                
                tmp_file.write(image_bytes)
                tmp_file.flush()
                
                # Convert to base64 for HTML embedding
                with open(tmp_file.name, 'rb') as f:
                    img_base64 = base64.b64encode(f.read()).decode('utf-8')
                
                # Clean up temporary file
                try:
                    os.unlink(tmp_file.name)
                except:
                    pass
                
                return f"""
                <div class="image-container">
                    <div class="image-label">📷 Asset Preview</div>
                    <img src="data:image/jpeg;base64,{img_base64}" 
                         alt="Asset Preview" class="asset-image">
                </div>
                """
                
        except Exception as e:
            print(f"⚠️ Error processing image: {e}")
            return self._generate_image_error_html()
    
    def _generate_image_error_html(self) -> str:
        """Generate HTML for image error display."""
        return """
        <div class="image-container">
            <div class="image-label">📷 Asset Preview</div>
            <div class="image-placeholder">
                📷 Image could not be displayed
            </div>
        </div>
        """
    
    def _generate_status_banner_html(self, compliance_status: str) -> str:
        """Generate HTML for status banner."""
        if compliance_status.lower() == 'compliant':
            return """
            <div class="status-banner compliant">
                ✅ COMPLIANT
            </div>
            """
        else:
            return """
            <div class="status-banner non-compliant">
                ⚠️ NON-COMPLIANT
            </div>
            """
    
    def _generate_findings_html(self, json_output: Dict[str, Any]) -> str:
        """Generate HTML for findings and recommendations."""
        violations = json_output.get('violations', [])
        
        if not violations:
            return """
            <div class="findings-section">
                <h2 class="section-title">🔍 Findings & Recommendations</h2>
                <p>No specific violation details available.</p>
            </div>
            """
        
        html = """
        <div class="findings-section">
            <h2 class="section-title">🔍 Findings & Recommendations</h2>
        """
        
        for i, violation in enumerate(violations, 1):
            rule_violated = violation.get('rule_violated', f'Violation {i}')
            description = violation.get('description', 'No description available')
            
            # Clean the description for business users
            clean_description = self._clean_text_for_business_users(description)
            if not clean_description:
                clean_description = "This element does not meet brand guidelines and needs to be corrected."
            
            # Use nested recommendation if available, otherwise generate one
            if violation.get('recommendation'):
                recommendation = self._clean_text_for_business_users(violation['recommendation'])
            else:
                recommendation = self._generate_user_friendly_recommendation(clean_description, rule_violated)
            
            html += f"""
            <div class="violation-item">
                <div class="violation-header">
                    ⚠️ Violation {i}: {rule_violated}
                </div>
                
                <div class="issue-section">
                    <div class="issue-label">🔍 Issue:</div>
                    <div class="issue-text">{clean_description}</div>
                </div>
                
                <div class="fix-section">
                    <div class="fix-label">🔧 Fix:</div>
                    <div class="fix-text">{recommendation}</div>
                </div>
            </div>
            """
        
        html += "</div>"
        return html
    
    def _generate_compliant_message_html(self, json_output: Dict[str, Any]) -> str:
        """Generate HTML for compliant asset message."""
        html = """
        <div class="compliant-message">
            <div class="compliant-title">✅ Excellent! This asset meets all brand guidelines.</div>
        """
        
        # Add summary if available
        summary = json_output.get('summary', '')
        if summary:
            clean_summary = self._clean_text_for_business_users(summary)
            if clean_summary and clean_summary != "Analysis completed":
                html += f"<p>{clean_summary}</p>"
        
        # Add recommendations
        recommendations = json_output.get('recommendations', [])
        if recommendations:
            html += """
            <div class="recommendations">
                <div class="fix-label">💡 Additional suggestions:</div>
            """
            for rec in recommendations:
                clean_rec = self._clean_text_for_business_users(rec)
                if clean_rec:
                    html += f"""
                    <div class="recommendation-item">
                        <span class="recommendation-bullet">•</span>
                        <span>{clean_rec}</span>
                    </div>
                    """
            html += "</div>"
        
        html += "</div>"
        return html
    
    def _clean_text_for_business_users(self, text: str) -> str:
        """Clean text to remove JSON formatting and make it business-friendly."""
        if not text:
            return ""
        
        # Remove JSON formatting characters
        cleaned = text.replace('```json', '').replace('```', '').replace('\\n', ' ')
        
        # Remove JSON structural elements
        import re
        cleaned = re.sub(r'[{}"\[\]]', '', cleaned)
        
        # Remove JSON field names
        cleaned = re.sub(r'(compliance_status|logo_type|summary|violations|recommendations|confidence_score):\s*', '', cleaned)
        
        # Clean up extra whitespace
        cleaned = re.sub(r'\s+', ' ', cleaned).strip()
        
        # If it still looks like JSON or is empty, return empty string
        if not cleaned or len(cleaned) < 10 or cleaned.startswith('{') or cleaned.endswith('}'):
            return ""
        
        # Ensure it ends with proper punctuation
        if cleaned and not cleaned.endswith(('.', '!', '?')):
            cleaned += '.'
        
        return cleaned
    
    def _generate_user_friendly_recommendation(self, description: str, rule_violated: str) -> str:
        """Convert technical descriptions into user-friendly recommendations."""
        # Rule-based mapping for common issues
        recommendations = {
            'alignment': 'Align the text to the left so its left edge lines up perfectly with the left edge of the Kia logo above it.',
            'color': 'Update the colors to match the official Kia brand colors specified in the brand guidelines.',
            'font': 'Change the font to the official Kia brand font as specified in the brand guidelines.',
            'spacing': 'Adjust the spacing between elements according to the brand guidelines measurements.',
            'logo': 'Ensure the Kia logo is used correctly without modifications and in the proper size ratio.',
            'proportion': 'Resize elements to match the correct proportions specified in the brand guidelines.',
            'position': 'Reposition the elements to match the correct layout specified in the brand guidelines.'
        }
        
        description_lower = description.lower()
        
        # Check for specific rule types
        for rule_type, recommendation in recommendations.items():
            if rule_type in description_lower or rule_type in rule_violated.lower():
                return recommendation
        
        # Generic recommendation if no specific rule is matched
        return "Please review this element against the brand guidelines and make the necessary adjustments to ensure compliance."


def generate_compliance_report_weasyprint(analysis_results: List[Dict[str, Any]], 
                                        session_metadata: Dict[str, Any] = None) -> bytes:
    """
    Generate a comprehensive compliance report using WeasyPrint with emoji support.
    
    Args:
        analysis_results: List of analysis result dictionaries
        session_metadata: Optional metadata about the session
        
    Returns:
        PDF file as bytes
    """
    print(f"🔍 DEBUG: generate_compliance_report_weasyprint called with {len(analysis_results)} results")
    
    generator = WeasyPrintBrandComplianceReportGenerator()
    print("🔍 DEBUG: ComplianceReportGenerator created, calling create_report...")
    
    result = generator.create_report(analysis_results, session_metadata)
    print(f"🔍 DEBUG: PDF creation completed, size: {len(result)} bytes")
    
    return result
