BEGIN;

CREATE TABLE IF NOT EXISTS projects (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(120) NOT NULL,
    description       TEXT NOT NULL DEFAULT '',
    settings          JSONB NOT NULL DEFAULT '{}'::jsonb,
    budget_limit      NUMERIC(10,2) NOT NULL DEFAULT 0,
    currency          VARCHAR(8) NOT NULL DEFAULT 'USD',
    last_opened_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS videos (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        INTEGER NOT NULL,
    original_path     VARCHAR(255) NOT NULL,
    storage_path      VARCHAR(255),
    duration_seconds  INTEGER,
    resolution        VARCHAR(32),
    status            VARCHAR(32) NOT NULL DEFAULT 'uploaded' CHECK (status IN ('uploaded', 'processed', 'failed')),
        metadata          JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_videos_project
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS inference_runs (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        INTEGER NOT NULL,
    video_id          INTEGER NOT NULL,
    model_ids         TEXT[] NOT NULL DEFAULT '{}'::text[],
    params            JSONB NOT NULL DEFAULT '{}'::jsonb,
    results           JSONB NOT NULL DEFAULT '{}'::jsonb,
    cost_actual       NUMERIC(10,4) NOT NULL DEFAULT 0,
    cost_projected    NUMERIC(10,4) NOT NULL DEFAULT 0,
    efficiency_ratio  NUMERIC(10,4) NOT NULL DEFAULT 0,
    status            VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'completed', 'failed')),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inference_runs_project
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_inference_runs_video
        FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_videos_project_id ON videos(project_id);
CREATE INDEX IF NOT EXISTS idx_inference_runs_project_id ON inference_runs(project_id);
CREATE INDEX IF NOT EXISTS idx_inference_runs_video_id ON inference_runs(video_id);

CREATE TABLE IF NOT EXISTS detections (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inference_run_id   INTEGER NOT NULL,
    frame_index        INTEGER,
    timestamp_seconds  NUMERIC(10,4),
    model_id           VARCHAR(64),
    label              VARCHAR(255),
    confidence         NUMERIC(5,4),
    bbox               JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_detections_inference_run
        FOREIGN KEY (inference_run_id) REFERENCES inference_runs(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_detections_inference_run_id ON detections(inference_run_id);
CREATE INDEX IF NOT EXISTS idx_detections_model_id ON detections(model_id);
CREATE INDEX IF NOT EXISTS idx_detections_timestamp_seconds ON detections(timestamp_seconds);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'videos'
          AND column_name = 'data'
    ) THEN
        ALTER TABLE videos RENAME COLUMN data TO metadata;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'trg_projects_set_updated_at'
    ) THEN
        CREATE TRIGGER trg_projects_set_updated_at
        BEFORE UPDATE ON projects
        FOR EACH ROW
        EXECUTE PROCEDURE set_updated_at();
    END IF;
END;
$$;

COMMIT;
