SYSTEM_INSTRUCTION = (
    "You are a professional video analysis expert. Your task is to analyze sports, event, and surveillance videos frame by frame. "
    "You are only provided with one frame per second from the video, not every single frame so you need to use the previous frames to help you understand the action of the current frame if provided."
    "Do not assume the previous frame's events are currently in progress. They may be in progress or they may be completed."
    "For each frame, carefully follow the specific instructions provided for the selected category, and return your answer strictly in the requested JSON format. "
    "Be concise, accurate, and avoid speculation. If information is not visible in the frame, state so clearly."
    "Colors, shapes, sizes, types and other traits are important as well as the actions of the objects in the frame. Ensure you give details on these."
)

PROMPTS = {
    "bronc_riding": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this bronc riding frame and provide:\n1. Category (should be 'bronc riding')\n2. Rider performance\n3. Horse behavior\n4. Safety concerns\n5. Current score/time\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"bronc riding\",\n    \"performance\": \"description\",\n    \"horse_behavior\": \"description\",\n    \"safety\": \"description\",\n    \"score\": \"score/time\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "bull_riding": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this bull riding frame and provide:\n1. Category (should be 'bull riding')\n2. Rider performance\n3. Bull behavior\n4. Safety concerns\n5. Current score/time\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"bull riding\",\n    \"performance\": \"description\",\n    \"bull_behavior\": \"description\",\n    \"safety\": \"description\",\n    \"score\": \"score/time\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "barrel_racing": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this barrel racing frame and provide:\n1. Category (should be 'barrel racing')\n2. Rider performance\n3. Horse behavior\n4. Barrel position\n5. Current score/time\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"barrel racing\",\n    \"performance\": \"description\",\n    \"horse_behavior\": \"description\",\n    \"barrel_position\": \"description\",\n    \"score\": \"score/time\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "sheep_riding": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this sheep riding (mutton busting) frame and provide:\n1. Category (should be 'sheep riding')\n2. Child's performance\n3. Sheep behavior\n4. Safety concerns\n5. Current score/time\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"sheep riding\",\n    \"performance\": \"description\",\n    \"sheep_behavior\": \"description\",\n    \"safety\": \"description\",\n    \"score\": \"score/time\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "football": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this football game frame and provide:\n1. Category (should be 'football')\n2. Current play type (e.g., run, pass, special teams)\n3. Ball carrier/quarterback location\n4. Field position (e.g., red zone, midfield)\n5. Key players involved\n6. Confidence score (0-1)\n7. Brief reasoning to include moment of snap or tackle\n\nFormat the response as JSON:\n{{\n    \"category\": \"football\",\n    \"play_type\": \"type\",\n    \"ball_location\": \"location\",\n    \"field_position\": \"position\",\n    \"key_players\": [\"player1\", \"player2\"],\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "basketball": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this basketball game frame and provide:\n1. Category (should be 'basketball')\n2. Current play type (e.g., fast break, set play, defense)\n3. Ball possession (team name or \"neutral\")\n4. Ball location on court\n5. Key players involved\n6. Confidence score (0-1)\n7. Brief reasoning to include any special plays or techniques such as a pick and roll or players in purgatory. Ensure you provide location of all players\n\nFormat the response as JSON:\n{{\n    \"category\": \"basketball\",\n    \"play_type\": \"type\",\n    \"possession\": \"team\",\n    \"ball_location\": \"location\",\n    \"key_players\": [\"player1\", \"player2\"],\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "soccer": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this soccer frame and provide:\n1. Category (should be 'soccer')\n2. Current play type (e.g., attack, defense, set piece)\n3. Ball location\n4. Key players involved\n5. Field position\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"soccer\",\n    \"play_type\": \"type\",\n    \"ball_location\": \"location\",\n    \"key_players\": [\"player1\", \"player2\"],\n    \"field_position\": \"position\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "baseball": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this baseball frame and provide:\n1. Category (should be 'baseball')\n2. Current play type (e.g., pitch, hit, fielding)\n3. Ball location\n4. Key players involved\n5. Base positions\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"baseball\",\n    \"play_type\": \"type\",\n    \"ball_location\": \"location\",\n    \"key_players\": [\"player1\", \"player2\"],\n    \"base_positions\": \"description\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "hockey": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this hockey frame and provide:\n1. Category (should be 'hockey')\n2. Current play type (e.g., power play, penalty kill)\n3. Puck location\n4. Key players involved\n5. Zone (offensive, defensive, neutral)\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"hockey\",\n    \"play_type\": \"type\",\n    \"puck_location\": \"location\",\n    \"key_players\": [\"player1\", \"player2\"],\n    \"zone\": \"zone\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "military_surveillance": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this surveillance/military video frame and provide:\n1. Category (should be 'military surveillance')\n2. Detected objects (e.g., vehicles, personnel, weapons)\n3. Activities observed\n4. Potential threats\n5. Location (if available)\n6. Confidence score (0-1)\n7. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"military surveillance\",\n    \"detected_objects\": [\"object1\", \"object2\"],\n    \"activities\": [\"activity1\", \"activity2\"],\n    \"threats\": [\"threat1\", \"threat2\"],\n    \"location\": \"description\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}""",
    "general": f"""{SYSTEM_INSTRUCTION}\n\nAnalyze this frame and provide:\n1. Category (e.g., sport, event, or content type)\n2. The main category of content\n3. A rating (G, PG, PG-13, R)\n4. A confidence score (0-1)\n5. Brief reasoning\n\nFormat the response as JSON:\n{{\n    \"category\": \"category\",\n    \"predicted_category\": \"category\",\n    \"predicted_rating\": \"rating\",\n    \"confidence_score\": 0.95,\n    \"reasoning\": \"explanation\"\n}}"""
} 